# Generated by Django 6.0.6 on 2026-07-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'middle_name', 'last_name']},
        ),
    ]
