"use client";

import { useState } from "react";
import { PlusCircle, Loader2, Calendar } from "lucide-react";

export default function AddSessionForm({
	onCreate, setAddSession
}: {
	onCreate: (data: { name: string; is_active: boolean }) => Promise<void>;
    setAddSession: React.Dispatch<React.SetStateAction<boolean>>;
}) {
	const [form, setForm] = useState({
		name: "",
		is_active: false,
	});

	const [loading, setLoading] = useState(false);
	const [error, setError] = useState("");
	const [success, setSuccess] = useState("");

	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const { name, value, type, checked } = e.target;

		setForm((prev) => ({
			...prev,
			[name]: type === "checkbox" ? checked : value,
		}));
	};

	const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();

		setLoading(true);
		setError("");
		setSuccess("");

		try {
			await onCreate(form);

			setSuccess("Session created successfully");

			setForm({
				name: "",
				is_active: false,
			});
			setAddSession(false);
		} catch (err: any) {
			setError(err?.message || "Something went wrong");
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className="w-full max-w-lg mx-auto">
			{/* CARD */}
			<div className="border bg-transparent w-full border-gray-200 rounded-2xl shadow-sm overflow-hidden">
				{/* HEADER */}
				<div className="flex items-center gap-3 bg-emerald-600 text-white px-5 py-4">
					<div className="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
						<Calendar size={20} />
					</div>

					<div>
						<h2 className="text-base font-semibold">
							Create Session
						</h2>
						<p className="text-xs text-emerald-100">
							Add a new academic session
						</p>
					</div>
				</div>

				{/* BODY */}
				<form onSubmit={handleSubmit} className="p- space-y-4">
					{/* INFO MESSAGE */}
					<div className="bg-yellow-50 border border-yellow-200 text-yellow-800 text-xs sm:text-sm p-3 rounded-xl">
						⚠️ Note: When a session is created, all required terms
						(First, Second, Third Term) will be automatically
						generated by the system.
					</div>

					{/* SESSION NAME */}
					<div>
						<label className="text-sm font-medium text-gray-700">
							Session Name
						</label>

						<input
							type="text"
							name="name"
							value={form.name}
							onChange={handleChange}
							placeholder="e.g. 2026/2027"
							className="mt-1 w-full px-4 py-3 rounded-xl border bg-gray-50 focus:ring-2 focus:ring-emerald-500 outline-none text-sm"
							required
						/>
					</div>

					{/* ACTIVE TOGGLE */}
					<div className="flex items-center justify-between bg-gray-50 border rounded-xl p-4">
						<div>
							<p className="text-sm font-medium text-gray-800">
								Set as Active Session
							</p>
							<p className="text-xs text-gray-500">
								This becomes the current session
							</p>
						</div>

						<label className="relative inline-flex items-center cursor-pointer">
							<input
								type="checkbox"
								name="is_active"
								checked={form.is_active}
								onChange={handleChange}
								className="sr-only peer"
							/>

							<div className="w-12 h-6 bg-gray-300 rounded-full peer peer-checked:bg-emerald-600 relative after:content-[''] after:absolute after:top-1 after:left-1 after:w-4 after:h-4 after:bg-white after:rounded-full after:transition-all peer-checked:after:translate-x-6" />
						</label>
					</div>

					{/* ERROR */}
					{error && (
						<div className="text-xs sm:text-sm text-red-600 bg-red-50 border border-red-200 p-2 rounded-lg">
							{error}
						</div>
					)}

					{/* SUCCESS */}
					{success && (
						<div className="text-xs sm:text-sm text-green-600 bg-green-50 border border-green-200 p-2 rounded-lg">
							{success}
						</div>
					)}

					{/* BUTTON */}
					<button
						type="submit"
						disabled={loading}
						className="w-full flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white py-3 rounded-xl font-medium transition"
					>
						{loading ? (
							<>
								<Loader2 className="animate-spin" size={18} />
								Creating...
							</>
						) : (
							<>
								<PlusCircle size={18} />
								Create Session
							</>
						)}
					</button>
				</form>
			</div>
		</div>
	);
}
