# Generated by Django 6.0.6 on 2026-07-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionbatch',
            name='promoted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionbatch',
            name='to_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_batches_to', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.promotionbatch'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='from_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.class'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='to_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.class'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='from_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rule', to='academics.class'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='to_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_promotions', to='academics.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.class'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsubjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_subjects', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionbatch',
            unique_together={('from_session', 'to_session')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='academics_s_admissi_70a43d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['parent_phone'], name='academics_s_parent__86bdae_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='academics_s_is_acti_af4dc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionrecord',
            unique_together={('batch', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student'], name='academics_s_student_18a209_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['session'], name='academics_s_session_d36bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['school_class'], name='academics_s_school__17dcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['is_current'], name='academics_s_is_curr_3cc8ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='unique_current_enrollment_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectteacher',
            unique_together={('class_subject', 'teacher', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'arm')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'session', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('school_class', 'subject', 'term')},
        ),
    ]
