# Generated by Django 6.0.4 on 2026-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_admitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
