# Generated by Django 6.0.6 on 2026-07-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__first_name', 'user__middle_name', 'user__last_name']},
        ),
    ]
