# Generated by Django 6.0.4 on 2026-06-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_student_date_admitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='created_at',
        ),
    ]
