# Generated by Django 6.0.4 on 2026-06-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_studentenrollment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arms',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class', to='academics.teacher'),
        ),
    ]
