# Generated by Django 6.0.6 on 2026-09-04 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PROMOTED', 'Promoted'), ('REPEATED', 'Repeated'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='ENROLLED', max_length=20)),
                ('student_snapshot', models.JSONField(default=dict)),
                ('class_snapshot', models.JSONField(default=dict)),
                ('session_snapshot', models.JSONField(default=dict)),
                ('term_snapshot', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='academics.studentenrollment')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_records', to='academics.class')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_records', to='academics.academicsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='academics.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_records', to='academics.term')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['student', 'session'], name='academics_s_student_8e2ff0_idx'), models.Index(fields=['session', 'school_class'], name='academics_s_session_301fa3_idx'), models.Index(fields=['session', 'status'], name='academics_s_session_67ef72_idx'), models.Index(fields=['term'], name='academics_s_term_id_12d0bc_idx'), models.Index(fields=['recorded_at'], name='academics_s_recorde_508823_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'session'), name='unique_student_history_per_session')],
            },
        ),
    ]
