# Generated by Django 6.0.6 on 2026-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionrule',
            options={'ordering': ['from_class__name']},
        ),
        migrations.AddConstraint(
            model_name='promotionrule',
            constraint=models.UniqueConstraint(fields=('from_class',), name='unique_promotion_rule_from_class'),
        ),
    ]
