# Generated by Django 6.0.6 on 2026-09-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_promotionrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrule',
            name='outcome',
            field=models.CharField(choices=[('PROMOTE', 'Promote'), ('GRADUATE', 'Graduate')], default='PROMOTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='to_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_promotions', to='academics.class'),
        ),
    ]
