# Generated by Django 6.0.4 on 2026-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentimport',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentimport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentimport',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
