# Generated by Django 6.0.6 on 2026-07-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
    ]
